### ISSUE TITLE
Note regarding what to push to public GitHub and what to keep within DLS GitLab

### ISSUE THREAD

**Issue by JamesOHeaDLS** [epics-containers/epics-containers.github.io#178]
Hello,

At the moment the wording in the 'Create a Generic IOC' section sounds like all modules should be pushed to GitHub.  However, talking to @coretl today, he mentioned that there will be quite a few DLS specific modules which won't benefit from moving to GitHub and can stay on GitLab.

It may be worth adding a note at the beginning of this section explaining how to decide where the repo should reside

Thanks,

James

**Comment by gilesknap** [comment]
@JamesOHeaDLS let me know if you are happy with the warning at the end of https://epics-containers.github.io/main/tutorials/generic_ioc.html#lakeshore-340-temperature-controller

**Comment by JamesOHeaDLS** [comment]
Thanks @gilesknap - yes that message is good although I think it would be worth saying what a PVC is/provide a link to more info about PVCs

> "....supply the proprietary library at runtime via a PVC"

**Comment by gilesknap** [comment]
Agreed. But I need to write a whole section on that. In the meantime I just wanted a note to say that there is a workaround to proprietary libraries.
