### ISSUE TITLE
Support for RTEMS

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/epics-containers.github.io#87]
Review support for RTEMS in light of the latest changes to the framework since the last RTEMS prototype.

First things to consider:
- how to set up the binaries folder
- new /dls_sw/rtems?
- all versions or just the current version?
- read up on the boot parameters and discuss the above with Paul
![image](https://github.com/epics-containers/epics-containers.github.io/assets/964827/5ce1e7ca-d72a-4e95-ba95-33a63ef397dd)

@coretl for comment.

**Comment by coretl** [comment]
Also need to consider how we get from binaries built locally and copied to a shared directory to k8s doing the copying

**Comment by gilesknap** [comment]
So I have solved all of this with the use of a nfsv2-tftp pod in the cluster. Including syncing to it from a devcontainer.

I am happy with this until the nfsv2/v4 thing is resolved and at that point we can make some decisions about where files are to go.

**Comment by gilesknap** [comment]
As per the above this has progressed and the RTEMS BSP plus base image for proxy are now in the org.
